[package]
    name              = "word-break"
    version.workspace = true

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
