[package]
    name    = "running-sum-of-1d-array"
    version = "0.1.0"

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
