[package]
    name              = "find-minimum-number-of-fibonacci-numbers-whose-sum-is-k"
    version.workspace = true

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
