[package]
    name              = "even-odd-tree"
    version.workspace = true

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
    utilities.workspace = true
