[package]
    name              = "minimum-amount-of-time-to-collect-garbage"
    version.workspace = true

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
