[package]
    name              = "flatten-nested-list-iterator"
    version.workspace = true

    authors.workspace = true

    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
