[package]
    name              = "find-minimum-in-rotated-sorted-array"
    version.workspace = true

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
