[package]
    name    = "divide-array-into-equal-parts"
    version = "0.1.0"

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
