[package]
    name    = "xor-queries-of-a-subarray"
    version = "0.1.0"

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
