[package]
    name    = "minimum_amount_of_time_to_collect_garbage"
    version = "0.1.0"

    authors.workspace      = true
    edition.workspace      = true
    publish.workspace      = true
    rust-version.workspace = true

[dependencies]
